MIN_SCORE = 1
MAX_SCORE = 10
NAME_LENGHT = 256
PAGINATION_PAGE_SIZE = 5
TEXT_LENGTH = 25

# views.py
PAGE_SIZE = 10
PAGE_SIZE_QUERY_PARAM = 'page_size'
MAX_PAGE_SIZE = 100

# serializers.py
EMAIL_MAX_LENGTH = 254
USERNAME_MAX_LENGTH = 150
CONFIRMATION_CODE_MAX_LENGTH = 128

# models.py
ROLE_MAX_LENGTH = 20

# upload_data.py
LOCATION_CSV = 'static/data/'
