import datetime

NAME_LENGHT = 256
SLUG_LENGHT = 50
TEXT_LENGTH = 25
THIS_YEAR = datetime.datetime.now().year


# views.py
PAGE_SIZE = 10
PAGE_SIZE_QUERY_PARAM = 'page_size'
MAX_PAGE_SIZE = 100

# serializers.py
EMAIL_MAX_LENGTH = 254
USERNAME_MAX_LENGTH = 150
CONFIRMATION_CODE_MAX_LENGTH = 128

# models.py
ROLE_MAX_LENGTH = 20
EMAIL_FIELD_MAX_LENGTH = 254