# Generated by Django 3.2 on 2024-07-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
