# Generated by Django 3.2 on 2024-07-06 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(2024)], verbose_name='Год выпуска'),
        ),
    ]
