# Generated by Django 3.2 on 2024-07-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_title_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(related_name='genre', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
