# Generated by Django 3.2 on 2024-07-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_title_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
