# Generated by Django 3.2 on 2024-07-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_title_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('id',), 'verbose_name': 'произведение', 'verbose_name_plural': 'произведения'},
        ),
    ]
